###########################################################
#                     DeadPool  Project
# DeadPool is a project that build base on the celery framework
# can support crawl multiple website on distribute machines.
###########################################################
#
# DeadPool Release Version
version: 1.0.0
#
# Base running connection Settings
connection:
  redis:
    host: "127.0.0.1"
    port: 6379
    database: 0
    username: "username"
    password: "password"
  mysql:
    host: "127.0.0.1"
    port: 3306
    database: "deadpool"
    username: "root"
    password: "password"
    timeout: 60
  mongodb:
    host: "127.0.0.1"
    port: 27017
    username: "username"
    password: "password"
  elasticsearch:
    host: "127.0.0.1"
    port: 9200
    index: "rlogs"
    username: "username"
    password: "password"

#
# Base Fundamental Settings
settings:
  cluster:
    name: "deadpool"
    node:
      role: "master"
      name: "node-1"
  #
  # Storage Settings
  # By default, if the task did not set the storage, it will storage in the mongodb
  storage:
    module:
      - "FileStorage"
      - "MongoStorage"
  #
  # ServerChan notify
  # By default, if the key is not set, will not send notify to wechat
  serverchan:
    key: sckey