#!/usr/bin/env bash

set -x
mkdir -p /data1/logs/deadpool
if ! getent group "goldeneye" >/dev/null; then
    groupadd -r "goldeneye"
fi

if ! getent group "celery" >/dev/null; then
    groupadd -r "celery"
fi

if ! getent passwd "celery" >/dev/null; then
    useradd -r -g "celery" -M --shell /bin/bash -c "celery service user" "celery"
fi
chown -R celery:celery /data1/logs/deadpool
set +x
